version: "3.9"
services:
  runner:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    env_file: .env
    # volumes:
    #   - .:/app
